apiVersion: v1
kind: Service
metadata:
    name: backend
    labels:
        name: backend-service
        app: webapp
spec:
    ports:
        - port: 3000
          targetPort: 3000
    selector:
        name: backend-pod
        app: webapp
