apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deploy
    labels:
        name: backend-deploy
        app: webapp
spec:
    replicas: 1
    selector:
        matchLabels:
            name: backend-pod
            app: webapp
    template:
        metadata:
            name: backend-pod
            labels:
                name: backend-pod
                app: webapp
        spec:
            containers:
                - name: webapp
                  image: muzlee/webapp-backend:1.1.0
                  env:
                      - name: REDIS_URL
                        value: 'redisdb'
                      - name: REDIS_PORT
                        value: '6379'
                      - name: PORT
                        value: '3000'
                  ports:
                      - containerPort: 3000
