apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend-service
    app: webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: frontend-pod
    app: webapp
